import "./globals.css";
import { Nunito } from "next/font/google";
import NavigationBar from "../components/NavigationBar";

const primary = Nunito({ subsets: ["latin"], weight: ["300", "600", "800"] });

export const metadata = {
  title: "World View",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-light-bg">
      <body className={primary.className}>
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
